version: '3.8'

services:
    db:
        build: ./postgresql
        ports:
            - '5432:5432'
        restart: unless-stopped
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        # networks:
        #   - app_network

    backend:
        build: ./backend
        ports:
            - '8080:8080'
        depends_on:
            - db
        env_file: .env
        # networks:
        #   - app_network
        network_mode: service:db

    # mock-api:
    #   build: ./mock-api
    #   ports:
    #     - "3000:3000"
    #   networks:
    #     - app_network

    # frontend:
    #   build: ./frontend
    #   ports:
    #     - "8000:8000"
    #   depends_on:
    #     - backend
    #   networks:
    #     - app_network

    # haproxy:
    #   build: ./haproxy
    #   ports:
    #     - "80:80"
    #   depends_on:
    #     - backend
    #     - frontend
    #   networks:
    #     - app_network

# networks:
#   app_network:
#     name: app_network

volumes:
    postgres-data:
